name: Build Tauri Meteor Template

on:
  push:
    branches: [ blink ]
  pull_request:
    branches: [ blink ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: setup Rust cache
      uses: actions/cache@v2
      with:
        key: ${{ matrix.os }}-${{ hashFiles('packages/admin/src-tauri/Cargo.lock') }}
        path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ./packages/admin/src-tauri/target
            
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install BUN Globally
      run: npm install -g bun

    - name: 🦀 Install Rust
      uses: actions-rs/toolchain@v1
      with: { toolchain: stable }

    - name: Install webkit2gtk (ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 librsvg2-dev patchelf
        
    - name: Install Bun.js dependencies
      run: bun install

    - name: Install Tauri CLI
      run: cargo install tauri-cli # Install Tauri dependencies

    - name: Build application
      run: bun run tauri build

    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.os }}
        path: src-tauri/target/release/bundle/**

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v0.1.0"
        release_name: "Blink Eye Release v0.1.0"
        draft: false
        prerelease: false

    - name: Upload .dmg, .exe, and .msi files to Release
      if: ${{ matrix.os == 'macos-latest' || matrix.os == 'windows-latest' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          src-tauri/target/release/bundle/dmg/*.dmg
          src-tauri/target/release/bundle/msi/*.msi
          src-tauri/target/release/bundle/nsis/*.exe
        asset_name: ${{ matrix.os }}-release
        asset_content_type: application/octet-stream
